all:
	g++ -std=c++11 -Wfatal-errors -I /global/cscratch1/sd/alvovsky/modules/cctbx_project/ -I /global/cscratch1/sd/alvovsky/build/include -I /global/cscratch1/sd/alvovsky/modules/ -I /global/cscratch1/sd/alvovsky/modules/boost/ -I /global/cscratch1/sd/alvovsky/conda_base/include/python2.7/ -o nanoBragg.exe main.cpp
