TARGET=nanoBragg.exe

all:
	g++ -std=c++11 -I /global/cscratch1/sd/alvovsky/modules/cctbx_project/ -I /global/cscratch1/sd/alvovsky/build/include -I /global/cscratch1/sd/alvovsky/modules/ -I /global/cscratch1/sd/alvovsky/modules/boost/ main.cpp -o $(TARGET)
clean:
	rm $(TARGET)
